name: Deploy backend-ts to AWS ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_TS }}:latest
          docker build -t $IMAGE_URI ./backend-ts
          docker push $IMAGE_URI

      - name: Replace placeholders in task definition
        run: |
          sed -i 's|PLACEHOLDER_DATABASE_URL|${{ secrets.DATABASE_URL }}|g' ecs-task-defs/backend-ts-task-def.json
          sed -i 's|PLACEHOLDER_DIRECT_URL|${{ secrets.DIRECT_URL }}|g' ecs-task-defs/backend-ts-task-def.json
          sed -i 's|PLACEHOLDER_BACKEND_PY_URL|${{ secrets.BACKEND_PY_URL }}|g' ecs-task-defs/backend-ts-task-def.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-defs/backend-ts-task-def.json
          container-name: backend-ts
          image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_TS }}:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          service: sb-ai-backend-ts-service
          cluster: sb-ai-cluster
          task-definition: ${{ steps.task-def.outputs.task-definition }}
